import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'

export default function Home() {
  return (
    <div className="container">    
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>LIFF Starter</title>
            <link rel="stylesheet" href="style.css">

            <script charset="utf-8" src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script>

            <style>
              body { background: #ECEFF1; color: rgba(0,0,0,0.87); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
              #message { background: white; max-width: 360px; margin: 100px auto 16px; padding: 32px 24px; border-radius: 3px; text-align: center;}
              #message h2 { color: #ffa100; font-weight: bold; font-size: 16px; margin: 0 0 8px; }
              #message h1 { font-size: 22px; font-weight: 300; color: rgba(0,0,0,0.6); margin: 0 0 16px; }
              #message p { line-height: 140%; margin: 16px 0 24px; font-size: 14px; }
              #message a { display: block; text-align: center; background: #039be5; text-transform: uppercase; text-decoration: none; color: white; padding: 16px; border-radius: 4px; }
              #message, #message a { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }
              #load { color: rgba(0,0,0,0.4); text-align: center; font-size: 13px; }
              @media (max-width: 600px) {
                body, #message { margin-top: 0; background: white; box-shadow: none; }
                body { border-top: 16px solid #ffa100; }
              }
            </style>
          </head>
          <body>

            <div id="message">
              <h2 id="head"></h2>
              <h1 id="show"></h1>    
            </div>

            <script>
              document.getElementById('head').textContent = "QR code scanner opening ..."

              liff.init({ liffId: 'LIFF_ID' }, () => {
                  // const idToken = liff.getDecodedIDToken();
                  // console.log(idToken) // print decoded idToken object
                  // displayLiffData()
                  scanQrCodeButton()
              });

              /**
              * Display data generated by invoking LIFF methods
              */
              function displayLiffData() {
                  let info = ""
                  info += liff.getLanguage() + '\r\n';
                  info += liff.getVersion() + '\r\n';
                  info +=  liff.isInClient() + '\r\n';
                  info +=  liff.isLoggedIn() + '\r\n';
                  info +=  liff.getOS() + '\r\n';
                  info +=  liff.getLineVersion() + '\r\n';
                  document.getElementById('show').textContent = info
              }

              // scanCode call
              function scanQrCodeButton() {
                if (!liff.isInClient()) {
                  sendAlertIfNotInClient();
                } else {
                  if (liff.scanCode) {
                      liff.scanCode().then(result => {
                          // e.g. result = { value: "Hello LIFF app!" }
                          const stringifiedResult = JSON.stringify(result);
                          document.getElementById('show').textContent = stringifiedResult
                          if(!result.value) return alert(result)
                          toggleQrCodeReader(result.value);
                      }).catch(err => {
                          document.getElementById('show').textContent = "scanCode failed! " + err;
                      });
                  }
                }
              }

              function sendAlertIfNotInClient() {
                alert('!liff.isInClient()')
              }

              function toggleQrCodeReader(qrText) {
                liff.sendMessages([{
                    'type': 'text',
                    'text': qrText
                }]).then(function() {
                    // window.alert('Message sent');
                    document.getElementById('head').textContent = "Message sended"
                    setTimeout(function(){ liff.closeWindow(); }, 1000);
                }).catch(function(error) {
                    window.alert('Error sending message: ' + error);
                });
              }


            </script>

          </body>
        </html>
            
    </div>
  )
}
